### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by Swanand01** [ffaanngg/pyston#2]
Hi, I have been trying to run the example in the readme file, but since today morning, I have been getting an SSLCertVerificationError, 

`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)`

`The above exception was the direct cause of the following exception:`
`aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host emkc.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)')]`

**Comment by Swanand01** [comment]
Please let me know if I should post the full Traceback.
Also, I checked emkc.org and their SSL Certificate seems to be valid

**Comment by shhivv** [comment]
Thanks for opening an issue!

I tried running the example code and I am getting the same error. I will try finding the solution.

**Comment by shhivv** [comment]
The linked issue seems to be related to this problem : https://github.com/aio-libs/aiohttp/issues/955

**Comment by Harmon758** [comment]
This is probably because of https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by shhivv** [comment]
> This is probably because of https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

That is interesting, I will look into that. Thanks for pointing it out.

**Comment by shhivv** [comment]
> Hi, I have been trying to run the example in the readme file, but since today morning, I have been getting an SSLCertVerificationError,
> 
> `ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)`
> 
> `The above exception was the direct cause of the following exception:` `aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host emkc.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)')]`

I have disabled the SSL verification while making a request which prevents the error from happening.

The module can be updated with `pip install -U aiopyston`

I have updated the docs at : http://aiopyston.readthedocs.io/

Thanks for opening an issue and please let me know if this works.
