### ISSUE TITLE
Typo in models?

### ISSUE THREAD

**Issue by ZeroAurora** [ffaanngg/pyston#3]
https://github.com/shhivv/pyston/blob/a1827f0385f79355f96576bc42940eed90611844/pyston/models.py#L8

and

https://github.com/shhivv/pyston/blob/a1827f0385f79355f96576bc42940eed90611844/pyston/models.py#L17

should be `stderr`, not `stdrr`

**Comment by shhivv** [comment]
yep, it appears to be a typo

thanks for pointing this out

**Comment by shhivv** [comment]
[fixed](https://github.com/shhivv/pyston/commit/24117581c7542a3083a6b9168c4ff474667d565c)
